sudo: false
branches:
  only:
  - master
language: node_js
node_js:
  - '10.12.0'
before_install:
  - npm i -g npm
install:
  - npm i npminstall && npminstall
before_script:
  - npm i -g gitbook-cli
script:
  - npm run build
after_script:
  - npminstall codecov && codecov
deploy:
  provider: pages
  local-dir: ./_dist
  target-branch: gh-pages
  fqdn: wiki.tfcloud.top
  skip-cleanup: true
  keep-history: false
  github-token: $GITHUB_TOKEN
  on:
    branch: master
notifications:
  slack:
    on_success: change